export const PERMISSIONS = [
  'dashboard.view',
  'analytics.view',
  'analytics.financial',
  'analytics.operations',
  'analytics.driver',
  'analytics.passenger',
  'analytics.export',
  'analytics.safety',
  'search.view',
  'users.view',
  'users.suspend',
  'users.impersonate',
  'users.vip',
  'kyc.view',
  'kyc.review',
  'kyc.approve',
  'kyc.reject',
  'kyc.override',
  'drivers.view',
  'drivers.activate',
  'vehicles.view',
  'rides.view',
  'rides.cancel',
  'offers.view',
  'map.view',
  'payments.view',
  'payments.refund',
  'finance.view',
  'pricing.view',
  'pricing.edit',
  'promos.view',
  'promos.edit',
  'cms.view',
  'cms.edit',
  'catalog.view',
  'catalog.edit',
  'ratings.view',
  'ratings.moderate',
  'chat.view',
  'chat.moderate',
  'risk.view',
  'risk.act',
  'cases.view',
  'cases.manage',
  'notifications.view',
  'notifications.send',
  'reports.export',
  'audit.view',
  'roles.manage',
  'settings.view',
  'settings.edit',
] as const;

export type Permission = (typeof PERMISSIONS)[number];

const ALL = [...PERMISSIONS];

const VIEWS = PERMISSIONS.filter((p) => p.endsWith('.view') || p === 'reports.export');

export const ROLE_SEEDS: Array<{
  slug: string;
  name: string;
  description: string;
  permissions: Permission[];
}> = [
  {
    slug: 'super-admin',
    name: 'Super Admin',
    description: 'Full control plane access',
    permissions: ALL,
  },
  {
    slug: 'operations',
    name: 'Operations Admin',
    description: 'Live ops, rides, drivers, KYC view, cases',
    permissions: [
      'dashboard.view',
      'analytics.view',
      'analytics.financial',
      'analytics.operations',
      'analytics.driver',
      'analytics.passenger',
      'analytics.export',
      'analytics.safety',
      'search.view',
      'users.view',
      'users.suspend',
      'kyc.view',
      'kyc.review',
      'kyc.approve',
      'kyc.reject',
      'drivers.view',
      'drivers.activate',
      'vehicles.view',
      'rides.view',
      'rides.cancel',
      'offers.view',
      'map.view',
      'chat.view',
      'cases.view',
      'cases.manage',
      'ratings.view',
      'audit.view',
      'settings.view',
    ],
  },
  {
    slug: 'kyc-officer',
    name: 'KYC Officer',
    description: 'Document review and driver activation',
    permissions: [
      'dashboard.view',
      'analytics.view',
      'search.view',
      'users.view',
      'kyc.view',
      'kyc.review',
      'kyc.approve',
      'kyc.reject',
      'kyc.override',
      'drivers.view',
      'drivers.activate',
      'vehicles.view',
      'audit.view',
    ],
  },
  {
    slug: 'finance',
    name: 'Finance Admin',
    description: 'Payments, refunds, earnings, reports',
    permissions: [
      'dashboard.view',
      'analytics.view',
      'analytics.financial',
      'analytics.export',
      'search.view',
      'users.view',
      'rides.view',
      'payments.view',
      'payments.refund',
      'finance.view',
      'pricing.view',
      'promos.view',
      'reports.export',
      'audit.view',
      'cases.view',
    ],
  },
  {
    slug: 'support',
    name: 'Support Agent',
    description: 'Cases, chat, impersonation, user 360',
    permissions: [
      'dashboard.view',
      'analytics.view',
      'analytics.safety',
      'search.view',
      'users.view',
      'users.impersonate',
      'drivers.view',
      'rides.view',
      'payments.view',
      'chat.view',
      'chat.moderate',
      'cases.view',
      'cases.manage',
      'ratings.view',
      'notifications.view',
    ],
  },
  {
    slug: 'content',
    name: 'Content Manager',
    description: 'CMS, catalog, FAQs, legal',
    permissions: [
      'dashboard.view',
      'analytics.view',
      'cms.view',
      'cms.edit',
      'catalog.view',
      'catalog.edit',
    ],
  },
  {
    slug: 'marketing',
    name: 'Marketing Manager',
    description: 'Promos, campaigns, VIP, notifications',
    permissions: [
      'dashboard.view',
      'analytics.view',
      'analytics.passenger',
      'search.view',
      'users.view',
      'users.vip',
      'promos.view',
      'promos.edit',
      'catalog.view',
      'notifications.view',
      'notifications.send',
    ],
  },
  {
    slug: 'analyst',
    name: 'Read-only Analyst',
    description: 'View and export only — no privileged mutations',
    permissions: [
      ...VIEWS.filter(
        (p) =>
          p !== 'users.impersonate' &&
          p !== 'payments.refund' &&
          p !== 'pricing.edit' &&
          p !== 'roles.manage',
      ),
      'analytics.financial',
      'analytics.operations',
      'analytics.driver',
      'analytics.passenger',
      'analytics.export',
      'analytics.safety',
    ],
  },
];
