-- Passenger booking / payment enrichment
ALTER TABLE "DriverProfile" ADD COLUMN IF NOT EXISTS "languagesJson" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "Ride" ADD COLUMN IF NOT EXISTS "viewCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "paymentMode" TEXT NOT NULL DEFAULT 'FULL';
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "onlineAmount" DECIMAL(12,2);
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "cashAmount" DECIMAL(12,2);
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "cashCurrency" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "paymentMethod" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "termsVersion" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "policyVersion" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "termsAcceptedAt" TIMESTAMP(3);
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "metaJson" JSONB;
